workerMachines = {
  'chatbot-channel-backend' => {
    'memory': '512',
    'cpus': 1,
    'box': 'ubuntu/jammy64',
    'ip': "192.168.56.21"
  },
  'chatbot-system-backend' => {
    'memory': '512',
    'cpus': 1,
    'box': 'ubuntu/jammy64',
    'ip': "192.168.56.22"
  },
  'torqvoice' => {
    'memory': '512',
    'cpus': 1,
    'box': 'ubuntu/jammy64',
    'ip': "192.168.56.23"
  },
  'vehicle-system-api' => {
    'memory': '512',
    'cpus': 1,
    'box': 'ubuntu/jammy64',
    'ip': "192.168.56.24"
  },
}

Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = "ubuntu/jammy64"
            master.vm.hostname = "master-#{i}"
            master.vm.network "private_network", ip: "192.168.56.1#{i}"

            master.ssh.insert_key = false
            master.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            master.vm.provision "shell", path: "common.sh"
            master.vm.provision "shell", path: "master.sh"

            master.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 2
              vb.memory = "2048"
            end
        end
    end

    workerMachines.each do |name, config|
        config.vm.define "#{name}" do |worker|
            worker.vm.box = config['box']
            worker.vm.hostname = "#{name}"
            worker.vm.network "private_network", ip: conf['ip']

            worker.ssh.insert_key = false
            worker.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            worker.vm.provision "shell", path: "common.sh"
            worker.vm.provision "shell", path: "worker.sh"

            worker.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = conf['cpus']
              vb.memory = conf['memory']
            end
        end
    end
end
