apiVersion: apps/v1
kind: Deployment
metadata:
  name: amn-vehicles-channel-backend
spec:
  selector:
    matchLabels:
      app: amn-vehicles-channel-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: amn-vehicles-channel-backend
    spec:
      containers:
      - name: amn-vehicles-channel
        image: amn-vehicles-channel:0.1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
          - containerPort: 4000