apiVersion: apps/v1
kind: Deployment
metadata:
  name: amn-vehicles-system-backend
spec:
  selector:
    matchLabels:
      app: amn-vehicles-system-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: amn-vehicles-system-backend
    spec:
      containers:
      - name: amn-vehicles-system
        image: amn-vehicles-system:0.1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
          - containerPort: 4000