version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  test:
    executor:
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm ci # Garante uma instalação limpa e idêntica ao lockfile
      - run:
          name: Install ts-node
          command: npm i -D ts-node
      - run:
          name: Run tests
          command: npm test

  deploy_surge:
    executor:
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm ci
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Install Surge
          command: npm install -g surge
      - run:
          name: Deploy to Surge
          command: surge ./out auto-mecanica-nelson.surge.sh

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
                - master
  test_and_deploy:
    jobs:
      # - test
      - deploy_surge:
          # requires:
          #   - test
          filters:
            branches:
              only:
                - master
