apiVersion: apps/v1
kind: Deployment
metadata:
  name: amn-frontend
spec:
  selector:
    matchLabels:
      app: amn-frontend
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: amn-frontend
    spec:
      containers:
      - name: amn-frontend
        image: amn-frontend:0.1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80