'use client';

import { useState } from "react";
import TopMenu from "@amn/components/TopMenu";
import Context from "@amn/stores";
// import type { Metadata } from "next";
import './globals.css';
import WebComponentLoader from "@amn/components/WebComponentLoader";

/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [themeMode, setThemeMode] = useState<'light' | 'dark'>('light');
  return (
    <Context.Provider value={{
      theme: {
        mode: themeMode,
        setMode: setThemeMode,
      },
    }}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <html lang="pt-br">
        <head>
          <WebComponentLoader />
        </head>
        <body>
          <TopMenu />
          {children}
        </body>
      </html>
    </Context.Provider>
  );
}
