import Context from "@amn/stores";
;import type { Metadata } from "next";
import TopMenu from "@amn/components/TopMenu";
import { useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

'use client';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [themeMode, setThemeMode] = useState<'light' | 'dark'>('light');
  return (
    <Context.Provider value={{
      theme: {
        mode: themeMode,
        setMode: setThemeMode,
      },
    }}>
      <html lang="en">
        <head></head>
        <body>
          <TopMenu />
          {children}
        </body>
      </html>
    </Context.Provider>
  );
}
